force-app/main/default/objects/FSAM_Customer_Asset__c/FSAM_Customer_Asset__c.object-meta.xml
<CustomObject>
    <label>FSAM Customer Asset</label>
    <nameField>
        <displayFormat>AST-{00000}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSAM Customer Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FSAM_Customer_Asset__c/fields/FSAM_Account__c.field-meta.xml
<CustomField>
    <fullName>FSAM_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Customer who owns the asset.</description>
    <inlineHelpText>Select the customer account that owns this asset.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FSAM Customer Assets</relationshipLabel>
    <relationshipName>FSAM_Customer_Assets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FSAM_Customer_Asset__c/fields/FSAM_Status__c.field-meta.xml
<CustomField>
    <fullName>FSAM_Status__c</fullName>
    <description>Current lifecycle state of the asset.</description>
    <inlineHelpText>Current lifecycle state of the asset.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Under Maintenance</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FSAM_Customer_Asset__c/fields/FSAM_Warranty_Active__c.field-meta.xml
<CustomField>
    <fullName>FSAM_Warranty_Active__c</fullName>
    <description>Automatically indicates whether the asset is currently under warranty.</description>
    <formula>AND(
    TODAY() &gt;= FSAM_Warranty_Start_Date__c,
    TODAY() &lt;= FSAM_Warranty_End_Date__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Automatically indicates whether the asset is currently under warranty.</inlineHelpText>
    <label>Warranty Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FSAM_Customer_Asset__c/fields/FSAM_Warranty_End_Date__c.field-meta.xml
<CustomField>
    <fullName>FSAM_Warranty_End_Date__c</fullName>
    <description>End date of warranty</description>
    <inlineHelpText>End date of warranty</inlineHelpText>
    <label>Warranty End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/selectors/FSAM_CustomerAssetSelector.cls
public with sharing class FSAM_CustomerAssetSelector {
    // return customer asset by Id
    public static List<FSAM_Customer_Asset__c> getByIds(Set<Id> assetIds){
        if(assetIds == null || assetIds.isEmpty()){
            return new List<FSAM_Customer_Asset__c>();
        }

        return [
            select Id, Name, FSAM_Status__c, FSAM_Warranty_Active__c, FSAM_Warranty_End_Date__c, FSAM_Account__c
            from FSAM_Customer_Asset__c
            where Id in :assetIds
        ];
    }

    // return avtive customer assets
    public static LIST<FSAM_Customer_Asset__c> getActiveAssets(){
        return [
            select Id, Name, FSAM_Status__c, FSAM_Warranty_Active__c, FSAM_Warranty_End_Date__c, FSAM_Account__c
            from FSAM_Customer_Asset__c
            where FSAM_Status__c = :FSAM_Constants.ASSET_STATUS_ACTIVE
        ];
    }
}